class PromotionOfferType:
    FLAT_DISCOUNT = "flat_discount"
    CASHBACK = "cashback"
    FREEBEE = "freebee"
    COUPON = "coupon"


class PromotionUserFrequency:
    FIRST_ORDER_EVER = "first_order_ever"
    FIRST_ORDER_APP = "first_order_app"
    FIRST_ORDER_POS = "first_order_pos"
    ANY = "any"


class PromotionErrorCode:
    PROMO_NOT_FOUND = "PROMO_NOT_FOUND"
    PROMO_EXPIRED = "PROMO_EXPIRED"
    PROMO_NOT_STARTED = "PROMO_NOT_STARTED"
    FACILITY_MISMATCH = "FACILITY_MISMATCH"
    CHANNEL_NOT_ALLOWED = "CHANNEL_NOT_ALLOWED"
    MIN_PURCHASE_NOT_MET = "MIN_PURCHASE_NOT_MET"
    PAYMENT_METHOD_NOT_ALLOWED = "PAYMENT_METHOD_NOT_ALLOWED"
    INVALID_PROMOTION = "INVALID_PROMOTION"
    NOT_FIRST_PURCHASE = "NOT_FIRST_PURCHASE"
    COUPON_USAGE_LIMIT_REACHED = "COUPON_USAGE_LIMIT_REACHED"
    COUPON_USER_LIMIT_REACHED = "COUPON_USER_LIMIT_REACHED"

